### ISSUE TITLE
Incomplete reset to QemuFSM from vm-node

### ISSUE THREAD

**Issue by likebreath** [SVL-PSU/crete-dev#33]
vm-node will reset the instance of QemuFSM if its flag::error is active. Relevant code: https://github.com/SVL-PSU/crete-dev/blob/71ab5f8f3c6116e1024219d6b93190102c956584/lib/cluster/vm_node.cpp#L62-L73)

This reset is incomplete, because it created a new instance of QemuFSM from scratch without keeping any useful information from the erred instance. For example, all tests and traces from the erred instance will be throwed away. 

A complete reset should keep all meaningful information, such as test cases and traces, from the erred instance.

**Comment by moralismercatus** [comment]
Hi @likebreath . 

Some clarifications.

From my vantage point, one test case yields one trace. I notice the use of plurals. Is that no longer the case? I.e., VM( TC ) -> trace? My understanding is that, at one time, a VM instance (QemuFSM) contains at most one TC and one trace.

The terminology may be a little confusing here. Just to be clear: _vm.reset()_ is more akin to hitting the reset button on a PC. It starts from scratch. Technically, _vm.reset()_ shouldn't be thought along those lines anyway because _vm_ is of type std::shared_ptr<QemuFSM>, so it's just resetting the pointer.

If by "complete reset" you mean "retry," then that's a little different. If a TC caused the VM to fail, retrying it could cause a loop if it fails consistently, so one must account for that.

I understand that it may be desirable to keep test case and trace info of a failed instance. Is your intent to preserve the test case and/or trace for some purpose, or to retry the test case upon failure?

Please let me know so I can more appropriately reply.

Thanks,

**Comment by likebreath** [comment]
@moralismercatus You are right. A VM instance will only operate on one TC and at most produce one trace.  I revisited the problem and found out that it was my misunderstanding.

Somehow, I thought the reset on VM instance (QemuFSM) as a reset on vm_node (which has a queue of TCs and Traces). I figured out that the order of TC being processed by VM instance is not always the same as the order of issuing TC from dispatch to vm_node. This is because the VM instance (QemuFSM) sometimes can't process TC (especially when a TC causing a VM instance failure):

https://github.com/SVL-PSU/crete-dev/blob/71ab5f8f3c6116e1024219d6b93190102c956584/lib/cluster/vm_node.cpp#L95-L110

The TC that is not processed is not thrown away, it is being pushed back to the TC queue of VM_Node (in line 107 of the above code). Also, it will be simple if we would like to keep the order. Let me know your thoughts. Thanks.

**Comment by moralismercatus** [comment]
@likebreath As I understand it, the event will fail to be handled when the guard fails. Essentially, if the previous action hasn't finished yet. I don't believe this HANDLED_TRUE check is relevant when the TC causes the VM to fail.

I see what you mean here about the TC being put back out of order. Yes, I believe this should push the TC to the front, instead of the back, as push() does.

**Comment by likebreath** [comment]
@moralismercatus I have a patch for imposing the order of processing TC ded235a9f859c5c181441cb4c4986b5bd71572bd (it is basically the same idea as yours). Please help me review it.

> I don't believe this HANDLED_TRUE check is relevant when the TC causes the VM to fail.

Conceptually, I agree. Empirically, everytime I have a VM failure (causing by a TC or a kill command), there is a "HANDLED_TRUE" check failure right after that. You should be able to easily reproduce it with adding few prints.

I believe this issue can be closed now.

**Comment by moralismercatus** [comment]
Very nice. Your fix is also more efficient than the original. Minor point in that ```auto t = ...;``` should probably be ```auto& t = ...;``` (implicitly const) or ```auto const& t = ...;```, to avoid a copy.

As for why a VM failure is followed by HANDLED_TRUE failure, I suspect that is because the VM/QEMU is still in the process of administering to the previous action, so the guard awaiting completion returns false.

Thanks, looks good!
